function saltsa(){
	document.getElementById('saltses').style.display='block';
	document.getElementById('snack').style.display='none';
	document.getElementById('artos').style.display='none';
	document.getElementById('EidiKatharismou').style.display='none';
	document.getElementById('EidhKatapsiksis').style.display='none';
	document.getElementById('EidiPantopoliou').style.display='none';
	document.getElementById('EidiSpitiou').style.display='none';
	document.getElementById('EidiPsigiou').style.display='none';
	document.getElementById('mpiskota').style.display='none';
	document.getElementById('zimarika').style.display='none';
	document.getElementById('kaba').style.display='none';
	document.getElementById('pets').style.display='none';
	document.getElementById('konserbes').style.display='none';
	document.getElementById('xartika').style.display='none';
	document.getElementById('proswpikiYgieinh').style.display='none';
	document.getElementById('YgieinhDiatrofi').style.display='none';
	document.getElementById('dwra').style.display='none';
	document.getElementById('slideshow-container').style.display='none';
	document.getElementById('sxolia').style.display='none';
}

function snack(){
	document.getElementById('saltses').style.display='none';
	document.getElementById('snack').style.display='block';
	document.getElementById('artos').style.display='none';
	document.getElementById('EidiKatharismou').style.display='none';
	document.getElementById('EidhKatapsiksis').style.display='none';
	document.getElementById('EidiPantopoliou').style.display='none';
	document.getElementById('EidiSpitiou').style.display='none';
	document.getElementById('EidiPsigiou').style.display='none';
	document.getElementById('mpiskota').style.display='none';
	document.getElementById('zimarika').style.display='none';
	document.getElementById('kaba').style.display='none';
	document.getElementById('pets').style.display='none';
	document.getElementById('konserbes').style.display='none';
	document.getElementById('xartika').style.display='none';
	document.getElementById('proswpikiYgieinh').style.display='none';
	document.getElementById('YgieinhDiatrofi').style.display='none';
	document.getElementById('dwra').style.display='none';
	document.getElementById('slideshow-container').style.display='none';
	document.getElementById('sxolia').style.display='none';
}

function artos(){
	document.getElementById('saltses').style.display='none';
	document.getElementById('snack').style.display='none';
	document.getElementById('artos').style.display='block';
	document.getElementById('EidiKatharismou').style.display='none';
	document.getElementById('EidhKatapsiksis').style.display='none';
	document.getElementById('EidiPantopoliou').style.display='none';
	document.getElementById('EidiSpitiou').style.display='none';
	document.getElementById('EidiPsigiou').style.display='none';
	document.getElementById('mpiskota').style.display='none';
	document.getElementById('zimarika').style.display='none';
	document.getElementById('kaba').style.display='none';
	document.getElementById('pets').style.display='none';
	document.getElementById('konserbes').style.display='none';
	document.getElementById('xartika').style.display='none';
	document.getElementById('proswpikiYgieinh').style.display='none';
	document.getElementById('YgieinhDiatrofi').style.display='none';
	document.getElementById('dwra').style.display='none';
	document.getElementById('slideshow-container').style.display='none';
	document.getElementById('sxolia').style.display='none';
}

function EidiKatharismou(){
	
	document.getElementById('saltses').style.display='none';
	document.getElementById('snack').style.display='none';
	document.getElementById('artos').style.display='none';
	document.getElementById('EidiKatharismou').style.display='block';
	document.getElementById('EidhKatapsiksis').style.display='none';
	document.getElementById('EidiPantopoliou').style.display='none';
	document.getElementById('EidiSpitiou').style.display='none';
	document.getElementById('EidiPsigiou').style.display='none';
	document.getElementById('mpiskota').style.display='none';
	document.getElementById('zimarika').style.display='none';
	document.getElementById('kaba').style.display='none';
	document.getElementById('pets').style.display='none';
	document.getElementById('konserbes').style.display='none';
	document.getElementById('xartika').style.display='none';
	document.getElementById('proswpikiYgieinh').style.display='none';
	document.getElementById('YgieinhDiatrofi').style.display='none';
	document.getElementById('dwra').style.display='none';
	document.getElementById('slideshow-container').style.display='none';
	document.getElementById('sxolia').style.display='none';
}

function EidiKatapsiksis(){
	document.getElementById('saltses').style.display='none';
	document.getElementById('snack').style.display='none';
	document.getElementById('artos').style.display='none';
	document.getElementById('EidiKatharismou').style.display='none';
	document.getElementById('EidhKatapsiksis').style.display='block';
	document.getElementById('EidiPantopoliou').style.display='none';
	document.getElementById('EidiSpitiou').style.display='none';
	document.getElementById('EidiPsigiou').style.display='none';
	document.getElementById('mpiskota').style.display='none';
	document.getElementById('zimarika').style.display='none';
	document.getElementById('kaba').style.display='none';
	document.getElementById('pets').style.display='none';
	document.getElementById('konserbes').style.display='none';
	document.getElementById('xartika').style.display='none';
	document.getElementById('proswpikiYgieinh').style.display='none';
	document.getElementById('YgieinhDiatrofi').style.display='none';
	document.getElementById('dwra').style.display='none';
	document.getElementById('slideshow-container').style.display='none';
	document.getElementById('sxolia').style.display='none';
}

function EidiPantopoliou(){
	document.getElementById('saltses').style.display='none';
	document.getElementById('snack').style.display='none';
	document.getElementById('artos').style.display='none';
	document.getElementById('EidiKatharismou').style.display='none';
	document.getElementById('EidhKatapsiksis').style.display='none';
	document.getElementById('EidiPantopoliou').style.display='block';
	document.getElementById('EidiSpitiou').style.display='none';
	document.getElementById('EidiPsigiou').style.display='none';
	document.getElementById('mpiskota').style.display='none';
	document.getElementById('zimarika').style.display='none';
	document.getElementById('kaba').style.display='none';
	document.getElementById('pets').style.display='none';
	document.getElementById('konserbes').style.display='none';
	document.getElementById('xartika').style.display='none';
	document.getElementById('proswpikiYgieinh').style.display='none';
	document.getElementById('YgieinhDiatrofi').style.display='none';
	document.getElementById('dwra').style.display='none';
	document.getElementById('slideshow-container').style.display='none';
	document.getElementById('sxolia').style.display='none';
}
function EidiSpitiou(){
	document.getElementById('saltses').style.display='none';
	document.getElementById('snack').style.display='none';
	document.getElementById('artos').style.display='none';
	document.getElementById('EidiKatharismou').style.display='none';
	document.getElementById('EidhKatapsiksis').style.display='none';
	document.getElementById('EidiPantopoliou').style.display='none';
	document.getElementById('EidiSpitiou').style.display='block';
	document.getElementById('EidiPsigiou').style.display='none';
	document.getElementById('mpiskota').style.display='none';
	document.getElementById('zimarika').style.display='none';
	document.getElementById('kaba').style.display='none';
	document.getElementById('pets').style.display='none';
	document.getElementById('konserbes').style.display='none';
	document.getElementById('xartika').style.display='none';
	document.getElementById('proswpikiYgieinh').style.display='none';
	document.getElementById('YgieinhDiatrofi').style.display='none';
	document.getElementById('dwra').style.display='none';
	document.getElementById('slideshow-container').style.display='none';
	document.getElementById('sxolia').style.display='none';
}

function EidiPsigiou(){
	document.getElementById('saltses').style.display='none';
	document.getElementById('snack').style.display='none';
	document.getElementById('artos').style.display='none';
	document.getElementById('EidiKatharismou').style.display='none';
	document.getElementById('EidhKatapsiksis').style.display='none';
	document.getElementById('EidiPantopoliou').style.display='none';
	document.getElementById('EidiSpitiou').style.display='none';
	document.getElementById('EidiPsigiou').style.display='block';
	document.getElementById('mpiskota').style.display='none';
	document.getElementById('zimarika').style.display='none';
	document.getElementById('kaba').style.display='none';
	document.getElementById('pets').style.display='none';
	document.getElementById('konserbes').style.display='none';
	document.getElementById('xartika').style.display='none';
	document.getElementById('proswpikiYgieinh').style.display='none';
	document.getElementById('YgieinhDiatrofi').style.display='none';
	document.getElementById('dwra').style.display='none';
	document.getElementById('slideshow-container').style.display='none';
	document.getElementById('sxolia').style.display='none';
}

function mpiskota(){
	document.getElementById('saltses').style.display='none';
	document.getElementById('snack').style.display='none';
	document.getElementById('artos').style.display='none';
	document.getElementById('EidiKatharismou').style.display='none';
	document.getElementById('EidhKatapsiksis').style.display='none';
	document.getElementById('EidiPantopoliou').style.display='none';
	document.getElementById('EidiSpitiou').style.display='none';
	document.getElementById('EidiPsigiou').style.display='none';
	document.getElementById('mpiskota').style.display='block';
	document.getElementById('zimarika').style.display='none';
	document.getElementById('kaba').style.display='none';
	document.getElementById('pets').style.display='none';
	document.getElementById('konserbes').style.display='none';
	document.getElementById('xartika').style.display='none';
	document.getElementById('proswpikiYgieinh').style.display='none';
	document.getElementById('YgieinhDiatrofi').style.display='none';
	document.getElementById('dwra').style.display='none';
	document.getElementById('slideshow-container').style.display='none';
	document.getElementById('sxolia').style.display='none';
}

function zimarika(){
	document.getElementById('saltses').style.display='none';
	document.getElementById('snack').style.display='none';
	document.getElementById('artos').style.display='none';
	document.getElementById('EidiKatharismou').style.display='none';
	document.getElementById('EidhKatapsiksis').style.display='none';
	document.getElementById('EidiPantopoliou').style.display='none';
	document.getElementById('EidiSpitiou').style.display='none';
	document.getElementById('EidiPsigiou').style.display='none';
	document.getElementById('mpiskota').style.display='none';
	document.getElementById('zimarika').style.display='block';
	document.getElementById('kaba').style.display='none';
	document.getElementById('pets').style.display='none';
	document.getElementById('konserbes').style.display='none';
	document.getElementById('xartika').style.display='none';
	document.getElementById('proswpikiYgieinh').style.display='none';
	document.getElementById('YgieinhDiatrofi').style.display='none';
	document.getElementById('dwra').style.display='none';
	document.getElementById('slideshow-container').style.display='none';
	document.getElementById('sxolia').style.display='none';
}
function kaba(){
	document.getElementById('saltses').style.display='none';
	document.getElementById('snack').style.display='none';
	document.getElementById('artos').style.display='none';
	document.getElementById('EidiKatharismou').style.display='none';
	document.getElementById('EidhKatapsiksis').style.display='none';
	document.getElementById('EidiPantopoliou').style.display='none';
	document.getElementById('EidiSpitiou').style.display='none';
	document.getElementById('EidiPsigiou').style.display='none';
	document.getElementById('mpiskota').style.display='none';
	document.getElementById('zimarika').style.display='none';
	document.getElementById('kaba').style.display='block';
	document.getElementById('pets').style.display='none';
	document.getElementById('konserbes').style.display='none';
	document.getElementById('xartika').style.display='none';
	document.getElementById('proswpikiYgieinh').style.display='none';
	document.getElementById('YgieinhDiatrofi').style.display='none';
	document.getElementById('dwra').style.display='none';
	document.getElementById('slideshow-container').style.display='none';
	document.getElementById('sxolia').style.display='none';
}

function pets(){
	document.getElementById('saltses').style.display='none';
	document.getElementById('snack').style.display='none';
	document.getElementById('artos').style.display='none';
	document.getElementById('EidiKatharismou').style.display='none';
	document.getElementById('EidhKatapsiksis').style.display='none';
	document.getElementById('EidiPantopoliou').style.display='none';
	document.getElementById('EidiSpitiou').style.display='none';
	document.getElementById('EidiPsigiou').style.display='none';
	document.getElementById('mpiskota').style.display='none';
	document.getElementById('zimarika').style.display='none';
	document.getElementById('kaba').style.display='none';
	document.getElementById('pets').style.display='block';
	document.getElementById('konserbes').style.display='none';
	document.getElementById('xartika').style.display='none';
	document.getElementById('proswpikiYgieinh').style.display='none';
	document.getElementById('YgieinhDiatrofi').style.display='none';
	document.getElementById('dwra').style.display='none';
	document.getElementById('slideshow-container').style.display='none';
	document.getElementById('sxolia').style.display='none';
}

function konserbes(){
	document.getElementById('saltses').style.display='none';
	document.getElementById('snack').style.display='none';
	document.getElementById('artos').style.display='none';
	document.getElementById('EidiKatharismou').style.display='none';
	document.getElementById('EidhKatapsiksis').style.display='none';
	document.getElementById('EidiPantopoliou').style.display='none';
	document.getElementById('EidiSpitiou').style.display='none';
	document.getElementById('EidiPsigiou').style.display='none';
	document.getElementById('mpiskota').style.display='none';
	document.getElementById('zimarika').style.display='none';
	document.getElementById('kaba').style.display='none';
	document.getElementById('pets').style.display='none';
	document.getElementById('konserbes').style.display='block';
	document.getElementById('xartika').style.display='none';
	document.getElementById('proswpikiYgieinh').style.display='none';
	document.getElementById('YgieinhDiatrofi').style.display='none';
	document.getElementById('dwra').style.display='none';
	document.getElementById('slideshow-container').style.display='none';
	document.getElementById('sxolia').style.display='none';
}

function xartika(){
	document.getElementById('saltses').style.display='none';
	document.getElementById('snack').style.display='none';
	document.getElementById('artos').style.display='none';
	document.getElementById('EidiKatharismou').style.display='none';
	document.getElementById('EidhKatapsiksis').style.display='none';
	document.getElementById('EidiPantopoliou').style.display='none';
	document.getElementById('EidiSpitiou').style.display='none';
	document.getElementById('EidiPsigiou').style.display='none';
	document.getElementById('mpiskota').style.display='none';
	document.getElementById('zimarika').style.display='none';
	document.getElementById('kaba').style.display='none';
	document.getElementById('pets').style.display='none';
	document.getElementById('konserbes').style.display='none';
	document.getElementById('xartika').style.display='block';
	document.getElementById('proswpikiYgieinh').style.display='none';
	document.getElementById('YgieinhDiatrofi').style.display='none';
	document.getElementById('dwra').style.display='none';
	document.getElementById('slideshow-container').style.display='none';
	document.getElementById('sxolia').style.display='none';
}

function proswpikiYgieinh(){
	document.getElementById('saltses').style.display='none';
	document.getElementById('snack').style.display='none';
	document.getElementById('artos').style.display='none';
	document.getElementById('EidiKatharismou').style.display='none';
	document.getElementById('EidhKatapsiksis').style.display='none';
	document.getElementById('EidiPantopoliou').style.display='none';
	document.getElementById('EidiSpitiou').style.display='none';
	document.getElementById('EidiPsigiou').style.display='none';
	document.getElementById('mpiskota').style.display='none';
	document.getElementById('zimarika').style.display='none';
	document.getElementById('kaba').style.display='none';
	document.getElementById('pets').style.display='none';
	document.getElementById('konserbes').style.display='none';
	document.getElementById('xartika').style.display='none';
	document.getElementById('proswpikiYgieinh').style.display='block';
	document.getElementById('YgieinhDiatrofi').style.display='none';
	document.getElementById('dwra').style.display='none';
	document.getElementById('slideshow-container').style.display='none';
	document.getElementById('sxolia').style.display='none';
}

function ygieinhDiatrofh(){
	document.getElementById('saltses').style.display='none';
	document.getElementById('snack').style.display='none';
	document.getElementById('artos').style.display='none';
	document.getElementById('EidiKatharismou').style.display='none';
	document.getElementById('EidhKatapsiksis').style.display='none';
	document.getElementById('EidiPantopoliou').style.display='none';
	document.getElementById('EidiSpitiou').style.display='none';
	document.getElementById('EidiPsigiou').style.display='none';
	document.getElementById('mpiskota').style.display='none';
	document.getElementById('zimarika').style.display='none';
	document.getElementById('kaba').style.display='none';
	document.getElementById('pets').style.display='none';
	document.getElementById('konserbes').style.display='none';
	document.getElementById('xartika').style.display='none';
	document.getElementById('proswpikiYgieinh').style.display='none';
	document.getElementById('YgieinhDiatrofi').style.display='block';
	document.getElementById('dwra').style.display='none';
	document.getElementById('slideshow-container').style.display='none';
	document.getElementById('sxolia').style.display='none';
}

function epoxiakaDwra(){
	document.getElementById('saltses').style.display='none';
	document.getElementById('snack').style.display='none';
	document.getElementById('artos').style.display='none';
	document.getElementById('EidiKatharismou').style.display='none';
	document.getElementById('EidhKatapsiksis').style.display='none';
	document.getElementById('EidiPantopoliou').style.display='none';
	document.getElementById('EidiSpitiou').style.display='none';
	document.getElementById('EidiPsigiou').style.display='none';
	document.getElementById('mpiskota').style.display='none';
	document.getElementById('zimarika').style.display='none';
	document.getElementById('kaba').style.display='none';
	document.getElementById('pets').style.display='none';
	document.getElementById('konserbes').style.display='none';
	document.getElementById('xartika').style.display='none';
	document.getElementById('proswpikiYgieinh').style.display='none';
	document.getElementById('YgieinhDiatrofi').style.display='none';
	document.getElementById('dwra').style.display='block';
	document.getElementById('slideshow-container').style.display='none';
	document.getElementById('sxolia').style.display='none';
}