function saltsa(){
	document.getElementById('saltses').style.display='block';
	document.getElementById('zimarika').style.display='none';
	document.getElementById('snack').style.display='none';
	document.getElementById('artozaxaroplasteio').style.display='none';
	document.getElementById('katapsikseis').style.display='none';
	document.getElementById('pantwpoleio').style.display='none';
	document.getElementById('psigio').style.display='none';
	document.getElementById('mpiskota').style.display='none';
	document.getElementById('kava').style.display='none';
	document.getElementById('konserves').style.display='none';
	document.getElementById('diatrofi').style.display='none';
	
}
function snack(){
	document.getElementById('saltses').style.display='none';
	document.getElementById('zimarika').style.display='none';
	document.getElementById('snack').style.display='block';
	document.getElementById('artozaxaroplasteio').style.display='none';
	document.getElementById('katapsikseis').style.display='none';
	document.getElementById('pantwpoleio').style.display='none';
	document.getElementById('psigio').style.display='none';
	document.getElementById('mpiskota').style.display='none';
	document.getElementById('kava').style.display='none';
	document.getElementById('konserves').style.display='none';
	document.getElementById('diatrofi').style.display='none';
}
function artozaxaroplasteio(){
	document.getElementById('saltses').style.display='none';
	document.getElementById('zimarika').style.display='none';
	document.getElementById('snack').style.display='none';
	document.getElementById('artozaxaroplasteio').style.display='block';
	document.getElementById('katapsikseis').style.display='none';
	document.getElementById('pantwpoleio').style.display='none';
	document.getElementById('psigio').style.display='none';
	document.getElementById('mpiskota').style.display='none';
	document.getElementById('kava').style.display='none';
	document.getElementById('konserves').style.display='none';
	document.getElementById('diatrofi').style.display='none';
}
function katapsiksi(){
	document.getElementById('saltses').style.display='none';
	document.getElementById('zimarika').style.display='none';
	document.getElementById('snack').style.display='none';
	document.getElementById('artozaxaroplasteio').style.display='none';
	document.getElementById('katapsikseis').style.display='block';
	document.getElementById('pantwpoleio').style.display='none';
	document.getElementById('psigio').style.display='none';
	document.getElementById('mpiskota').style.display='none';
	document.getElementById('kava').style.display='none';
	document.getElementById('konserves').style.display='none';
	document.getElementById('diatrofi').style.display='none';
}
function pantopwleio(){
	document.getElementById('saltses').style.display='none';
	document.getElementById('zimarika').style.display='none';
	document.getElementById('snack').style.display='none';
	document.getElementById('artozaxaroplasteio').style.display='none';
	document.getElementById('katapsikseis').style.display='none';
	document.getElementById('pantwpoleio').style.display='block';
	document.getElementById('psigio').style.display='none';
	document.getElementById('mpiskota').style.display='none';
	document.getElementById('kava').style.display='none';
	document.getElementById('konserves').style.display='none';
	document.getElementById('diatrofi').style.display='none';
}
function psigio(){
	document.getElementById('saltses').style.display='none';
	document.getElementById('zimarika').style.display='none';
	document.getElementById('snack').style.display='none';
	document.getElementById('artozaxaroplasteio').style.display='none';
	document.getElementById('katapsikseis').style.display='none';
	document.getElementById('pantwpoleio').style.display='none';
	document.getElementById('psigio').style.display='block';
	document.getElementById('mpiskota').style.display='none';
	document.getElementById('kava').style.display='none';
	document.getElementById('konserves').style.display='none';
	document.getElementById('diatrofi').style.display='none';
}
function mpiskota(){
	document.getElementById('saltses').style.display='none';
	document.getElementById('zimarika').style.display='none';
	document.getElementById('snack').style.display='none';
	document.getElementById('artozaxaroplasteio').style.display='none';
	document.getElementById('katapsikseis').style.display='none';
	document.getElementById('pantwpoleio').style.display='none';
	document.getElementById('psigio').style.display='none';
	document.getElementById('mpiskota').style.display='block';
	document.getElementById('kava').style.display='none';
	document.getElementById('konserves').style.display='none';
	document.getElementById('diatrofi').style.display='none';
}
function zimarika(){
	document.getElementById('saltses').style.display='none';
	document.getElementById('zimarika').style.display='block';
	document.getElementById('snack').style.display='none';
	document.getElementById('artozaxaroplasteio').style.display='none';
	document.getElementById('katapsikseis').style.display='none';
	document.getElementById('pantwpoleio').style.display='none';
	document.getElementById('psigio').style.display='none';
	document.getElementById('mpiskota').style.display='none';
	document.getElementById('kava').style.display='none';
	document.getElementById('konserves').style.display='none';
	document.getElementById('diatrofi').style.display='none';
}
function kava(){
	document.getElementById('saltses').style.display='none';
	document.getElementById('zimarika').style.display='none';
	document.getElementById('snack').style.display='none';
	document.getElementById('artozaxaroplasteio').style.display='none';
	document.getElementById('katapsikseis').style.display='none';
	document.getElementById('pantwpoleio').style.display='none';
	document.getElementById('psigio').style.display='none';
	document.getElementById('mpiskota').style.display='none';
	document.getElementById('kava').style.display='block';
	document.getElementById('konserves').style.display='none';
	document.getElementById('diatrofi').style.display='none';
}
function konserva(){
	document.getElementById('saltses').style.display='none';
	document.getElementById('zimarika').style.display='none';
	document.getElementById('snack').style.display='none';
	document.getElementById('artozaxaroplasteio').style.display='none';
	document.getElementById('katapsikseis').style.display='none';
	document.getElementById('pantwpoleio').style.display='none';
	document.getElementById('psigio').style.display='none';
	document.getElementById('mpiskota').style.display='none';
	document.getElementById('kava').style.display='none';
	document.getElementById('konserves').style.display='block';
	document.getElementById('diatrofi').style.display='none';
}
function diatrofi(){
	document.getElementById('saltses').style.display='none';
	document.getElementById('zimarika').style.display='none';
	document.getElementById('snack').style.display='none';
	document.getElementById('artozaxaroplasteio').style.display='none';
	document.getElementById('katapsikseis').style.display='none';
	document.getElementById('pantwpoleio').style.display='none';
	document.getElementById('psigio').style.display='none';
	document.getElementById('mpiskota').style.display='none';
	document.getElementById('kava').style.display='none';
	document.getElementById('konserves').style.display='none';
	document.getElementById('diatrofi').style.display='block';
}