function taktopoihshs(){
	document.getElementById('taktopoihshs').style.display='block';
	document.getElementById('mpanio').style.display='none';
	document.getElementById('plastika').style.display='none';
	document.getElementById('skoupes').style.display='none';
	document.getElementById('kouzinas').style.display='none';
	document.getElementById('mpataries').style.display='none';
	document.getElementById('aksesouar').style.display='none';
	document.getElementById('siskeues').style.display='none';
	document.getElementById('miasxrisis').style.display='none';
	document.getElementById('alouminiou').style.display='none';
	document.getElementById('aporimatwn').style.display='none';
	document.getElementById('katoikidia').style.display='none';
	document.getElementById('diafora').style.display='none';
}
function mpaniou(){
	document.getElementById('taktopoihshs').style.display='none';
	document.getElementById('mpanio').style.display='block';
	document.getElementById('plastika').style.display='none';
	document.getElementById('skoupes').style.display='none';
	document.getElementById('kouzinas').style.display='none';
	document.getElementById('mpataries').style.display='none';
	document.getElementById('aksesouar').style.display='none';
	document.getElementById('siskeues').style.display='none';
	document.getElementById('miasxrisis').style.display='none';
	document.getElementById('alouminiou').style.display='none';
	document.getElementById('aporimatwn').style.display='none';
	document.getElementById('katoikidia').style.display='none';
	document.getElementById('diafora').style.display='none';
}
function plastika(){
	document.getElementById('taktopoihshs').style.display='none';
	document.getElementById('mpanio').style.display='none';
	document.getElementById('plastika').style.display='block';
	document.getElementById('skoupes').style.display='none';
	document.getElementById('kouzinas').style.display='none';
	document.getElementById('mpataries').style.display='none';
	document.getElementById('aksesouar').style.display='none';
	document.getElementById('siskeues').style.display='none';
	document.getElementById('miasxrisis').style.display='none';
	document.getElementById('alouminiou').style.display='none';
	document.getElementById('aporimatwn').style.display='none';
	document.getElementById('katoikidia').style.display='none';
	document.getElementById('diafora').style.display='none';
} 
function skoupes(){
	document.getElementById('taktopoihshs').style.display='none';
	document.getElementById('mpanio').style.display='none';
	document.getElementById('plastika').style.display='none';
	document.getElementById('skoupes').style.display='block';
	document.getElementById('kouzinas').style.display='none';
	document.getElementById('mpataries').style.display='none';
	document.getElementById('aksesouar').style.display='none';
	document.getElementById('siskeues').style.display='none';
	document.getElementById('miasxrisis').style.display='none';
	document.getElementById('alouminiou').style.display='none';
	document.getElementById('aporimatwn').style.display='none';
	document.getElementById('katoikidia').style.display='none';
	document.getElementById('diafora').style.display='none';
}
function kouzinas(){
	document.getElementById('taktopoihshs').style.display='none';
	document.getElementById('mpanio').style.display='none';
	document.getElementById('plastika').style.display='none';
	document.getElementById('skoupes').style.display='none';
	document.getElementById('kouzinas').style.display='block';
	document.getElementById('mpataries').style.display='none';
	document.getElementById('aksesouar').style.display='none';
	document.getElementById('siskeues').style.display='none';
	document.getElementById('miasxrisis').style.display='none';
	document.getElementById('alouminiou').style.display='none';
	document.getElementById('aporimatwn').style.display='none';
	document.getElementById('katoikidia').style.display='none';
	document.getElementById('diafora').style.display='none';
}
function mpataries(){
	document.getElementById('taktopoihshs').style.display='none';
	document.getElementById('mpanio').style.display='none';
	document.getElementById('plastika').style.display='none';
	document.getElementById('skoupes').style.display='none';
	document.getElementById('kouzinas').style.display='none';
	document.getElementById('mpataries').style.display='block';
	document.getElementById('aksesouar').style.display='none';
	document.getElementById('siskeues').style.display='none';
	document.getElementById('miasxrisis').style.display='none';
	document.getElementById('alouminiou').style.display='none';
	document.getElementById('aporimatwn').style.display='none';
	document.getElementById('katoikidia').style.display='none';
	document.getElementById('diafora').style.display='none';
}
function aksesouar(){
	document.getElementById('taktopoihshs').style.display='none';
	document.getElementById('mpanio').style.display='none';
	document.getElementById('plastika').style.display='none';
	document.getElementById('skoupes').style.display='none';
	document.getElementById('kouzinas').style.display='none';
	document.getElementById('mpataries').style.display='none';
	document.getElementById('aksesouar').style.display='block';
	document.getElementById('siskeues').style.display='none';
	document.getElementById('miasxrisis').style.display='none';
	document.getElementById('alouminiou').style.display='none';
	document.getElementById('aporimatwn').style.display='none';
	document.getElementById('katoikidia').style.display='none';
	document.getElementById('diafora').style.display='none';
}
function siskeues(){
	document.getElementById('taktopoihshs').style.display='none';
	document.getElementById('mpanio').style.display='none';
	document.getElementById('plastika').style.display='none';
	document.getElementById('skoupes').style.display='none';
	document.getElementById('kouzinas').style.display='none';
	document.getElementById('mpataries').style.display='none';
	document.getElementById('aksesouar').style.display='none';
	document.getElementById('siskeues').style.display='block';
	document.getElementById('miasxrisis').style.display='none';
	document.getElementById('alouminiou').style.display='none';
	document.getElementById('aporimatwn').style.display='none';
	document.getElementById('katoikidia').style.display='none';
	document.getElementById('diafora').style.display='none';
}
function miasxrisis(){
	document.getElementById('taktopoihshs').style.display='none';
	document.getElementById('mpanio').style.display='none';
	document.getElementById('plastika').style.display='none';
	document.getElementById('skoupes').style.display='none';
	document.getElementById('kouzinas').style.display='none';
	document.getElementById('mpataries').style.display='none';
	document.getElementById('aksesouar').style.display='none';
	document.getElementById('siskeues').style.display='none';
	document.getElementById('miasxrisis').style.display='block';
	document.getElementById('alouminiou').style.display='none';
	document.getElementById('aporimatwn').style.display='none';
	document.getElementById('katoikidia').style.display='none';
	document.getElementById('diafora').style.display='none';
}
function alouminiou(){
	document.getElementById('taktopoihshs').style.display='none';
	document.getElementById('mpanio').style.display='none';
	document.getElementById('plastika').style.display='none';
	document.getElementById('skoupes').style.display='none';
	document.getElementById('kouzinas').style.display='none';
	document.getElementById('mpataries').style.display='none';
	document.getElementById('aksesouar').style.display='none';
	document.getElementById('siskeues').style.display='none';
	document.getElementById('miasxrisis').style.display='none';
	document.getElementById('alouminiou').style.display='block';
	document.getElementById('aporimatwn').style.display='none';
	document.getElementById('katoikidia').style.display='none';
	document.getElementById('diafora').style.display='none';
}
function aporimatwn(){
	document.getElementById('taktopoihshs').style.display='none';
	document.getElementById('mpanio').style.display='none';
	document.getElementById('plastika').style.display='none';
	document.getElementById('skoupes').style.display='none';
	document.getElementById('kouzinas').style.display='none';
	document.getElementById('mpataries').style.display='none';
	document.getElementById('aksesouar').style.display='none';
	document.getElementById('siskeues').style.display='none';
	document.getElementById('miasxrisis').style.display='none';
	document.getElementById('alouminiou').style.display='none';
	document.getElementById('aporimatwn').style.display='block';
	document.getElementById('katoikidia').style.display='none';
	document.getElementById('diafora').style.display='none';
}
function katoikidia(){
	document.getElementById('taktopoihshs').style.display='none';
	document.getElementById('mpanio').style.display='none';
	document.getElementById('plastika').style.display='none';
	document.getElementById('skoupes').style.display='none';
	document.getElementById('kouzinas').style.display='none';
	document.getElementById('mpataries').style.display='none';
	document.getElementById('aksesouar').style.display='none';
	document.getElementById('siskeues').style.display='none';
	document.getElementById('miasxrisis').style.display='none';
	document.getElementById('alouminiou').style.display='none';
	document.getElementById('aporimatwn').style.display='none';
	document.getElementById('katoikidia').style.display='block';
	document.getElementById('diafora').style.display='none';
}
function diafora(){
	document.getElementById('taktopoihshs').style.display='none';
	document.getElementById('mpanio').style.display='none';
	document.getElementById('plastika').style.display='none';
	document.getElementById('skoupes').style.display='none';
	document.getElementById('kouzinas').style.display='none';
	document.getElementById('mpataries').style.display='none';
	document.getElementById('aksesouar').style.display='none';
	document.getElementById('siskeues').style.display='none';
	document.getElementById('miasxrisis').style.display='none';
	document.getElementById('alouminiou').style.display='none';
	document.getElementById('aporimatwn').style.display='none';
	document.getElementById('katoikidia').style.display='none';
	document.getElementById('diafora').style.display='block';
}